# Generated by Django 3.1.2 on 2020-10-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='principal',
            field=models.CharField(default='null', max_length=256),
        ),
    ]
