# Generated by Django 3.1.2 on 2020-10-12 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('entity_name', models.CharField(max_length=264)),
                ('Tax_regno', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=264)),
                ('Reg_date', models.DateField()),
                ('cont_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_name', models.CharField(max_length=264)),
                ('no_ppl', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('place', models.CharField(max_length=294)),
                ('description', models.CharField(max_length=294)),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=294, unique=True)),
                ('description', models.CharField(max_length=294)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.program')),
            ],
        ),
    ]
