# Generated by Django 3.1.2 on 2020-10-12 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20201012_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.actor')),
                ('Funct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.funtions')),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.topic')),
            ],
        ),
    ]
